public class ExceptionDemo {

   /* public static void main(String[] args) {
        int i = 0;
        int[] m = {1, 2, 3};

        System.out.println(metodas(m, 2));

        public static void myFunc() {
            System.out.println("My Function called");
        }

        public int metodas(m,  i) {
            return m[i];
        }

    }

    */

}
